name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Generate Docs and push
      run: |
        mkdir docs && cd docs
        git init
        git config --global users.name "${{ secrets.GH_USER }}"
        git config --global user.email "${{ secrets.GH_MAIL }}"
        git remote add gh-token "https://${{ secrets.GH_TOKEN}}@github.com/realbucksavage/openrgb-go"
        git fetch gh-token && git fetch gh-token docs:docs
        rm -r ./* && cd ..
        
        go get github.com/robertkrimen/godocdown/godocdown
        godocdown > docs/README.md
        
        cd docs
        git add .
        git commit -m "Updated docs"
        git push gh-token docs
        
